# Este archivo es para configurar la utilizacion de los recursos que el API va a utilizar
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
    python_version: 3


manual_scaling:
   instances: 1
resources:
   cpu: 1
   memory_gb: 0.5
   disk_size_gb: 10